#================================================================
# CORE Training & Simulation Environment - GPU-Accelerated 
#================================================================
# Usage:
#
#================================================================
networks:
  core:
    driver: bridge

services:
  redis: 
      image: redis:8.6.1
      container_name: redis
      ports:
        - '6379:6379'
      volumes:
        - ./data/redis-data:/data
      environment:
        - REDIS_ARGS=--requirepass $REDIS_PASS --appendonly yes --loglevel warning
      restart: unless-stopped
      networks:
        - core

  mlflow:
      image: ghcr.io/mlflow/mlflow:v2.16.0
      container_name: mlflow
      command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:////mlruns/mlflow.db --default-artifact-root /mlruns
      volumes: 
        - ./data/mlruns:/mlruns
      ports: 
        - '5000:5000'
      restart: unless-stopped
      networks:
        - core
  
  env:
    container_name: env
    build:
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ../src:/ros2_ws/core/src
        - /dev/dri:/dev/dri
        - ./data/models:/ros2_ws/core/models
    environment:
        - DISPLAY=${DISPLAY}
        - XDG_RUNTIME_DIR=/tmp/runtime-root
        - SDL_AUDIODRIVER=dummy
        - ROBOT_PKG=${ROBOT_PKG:-}
    ports:
      - '50051:50051'
      - '8765:8765'
    restart: unless-stopped
    depends_on:
      - redis
      - mlflow
    networks:
      - core
  
  env-gpu:
    extends:
      service: env
    container_name: env
    profiles: ["gpu"]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:  [gpu, graphics, display]

